/**
 * Seeder Script for Currency, DateFormat, TimeFormat, and Timezones
 * Run: node seedDefaults.js
 */

import mongoose from 'mongoose';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/kanakku';

await mongoose.connect(MONGO_URI);
console.log('Connected to MongoDB');

const Currency = mongoose.model('Currency', new mongoose.Schema({
  name: String,
  code: String,
  symbol: String,
  isDefault: { type: Boolean, default: false },
  isActive: { type: Boolean, default: true }
}));

const DateFormat = mongoose.model('DateFormat', new mongoose.Schema({
  title: String,
  format: String,
  isActive: Boolean,
  isDeleted: Boolean
}));

const TimeFormat = mongoose.model('TimeFormat', new mongoose.Schema({
  name: String,
  format: String,
  isActive: Boolean,
  isDeleted: Boolean
}));

const Timezone = mongoose.model('Timezone', new mongoose.Schema({
  name: String,
  utc_offset: String
}));


//Currencies
const currencies = [
  { name: 'US Dollar', code: 'USD', symbol: '$', isDefault: true },
  { name: 'Euro', code: 'EUR', symbol: '€' },
  { name: 'British Pound', code: 'GBP', symbol: '£' },
  { name: 'Indian Rupee', code: 'INR', symbol: '₹' },
  { name: 'Australian Dollar', code: 'AUD', symbol: 'A$' },
  { name: 'Canadian Dollar', code: 'CAD', symbol: 'C$' },
  { name: 'Japanese Yen', code: 'JPY', symbol: '¥' },
  { name: 'Chinese Yuan', code: 'CNY', symbol: '¥' },
  { name: 'Swiss Franc', code: 'CHF', symbol: 'CHF' },
  { name: 'Hong Kong Dollar', code: 'HKD', symbol: 'HK$' },
  { name: 'New Zealand Dollar', code: 'NZD', symbol: 'NZ$' },
  { name: 'Swedish Krona', code: 'SEK', symbol: 'kr' },
  { name: 'South Korean Won', code: 'KRW', symbol: '₩' },
  { name: 'Singapore Dollar', code: 'SGD', symbol: 'S$' },
  { name: 'Norwegian Krone', code: 'NOK', symbol: 'kr' },
  { name: 'Mexican Peso', code: 'MXN', symbol: '$' },
  { name: 'Russian Ruble', code: 'RUB', symbol: '₽' },
  { name: 'South African Rand', code: 'ZAR', symbol: 'R' },
  { name: 'Turkish Lira', code: 'TRY', symbol: '₺' },
  { name: 'Brazilian Real', code: 'BRL', symbol: 'R$' },
  { name: 'Danish Krone', code: 'DKK', symbol: 'kr' },
  { name: 'Polish Zloty', code: 'PLN', symbol: 'zł' },
  { name: 'Thai Baht', code: 'THB', symbol: '฿' },
  { name: 'Indonesian Rupiah', code: 'IDR', symbol: 'Rp' },
  { name: 'Hungarian Forint', code: 'HUF', symbol: 'Ft' },
  { name: 'Czech Koruna', code: 'CZK', symbol: 'Kč' },
  { name: 'Israeli New Shekel', code: 'ILS', symbol: '₪' },
  { name: 'Chilean Peso', code: 'CLP', symbol: '$' },
  { name: 'Philippine Peso', code: 'PHP', symbol: '₱' },
  { name: 'UAE Dirham', code: 'AED', symbol: 'د.إ' },
  { name: 'Colombian Peso', code: 'COP', symbol: '$' },
  { name: 'Saudi Riyal', code: 'SAR', symbol: '﷼' },
  { name: 'Malaysian Ringgit', code: 'MYR', symbol: 'RM' },
  { name: 'Romanian Leu', code: 'RON', symbol: 'lei' },
  { name: 'Vietnamese Dong', code: 'VND', symbol: '₫' },
  { name: 'Peruvian Sol', code: 'PEN', symbol: 'S/' },
  { name: 'Bangladeshi Taka', code: 'BDT', symbol: '৳' },
  { name: 'Ukrainian Hryvnia', code: 'UAH', symbol: '₴' },
  { name: 'Egyptian Pound', code: 'EGP', symbol: '£' },
  { name: 'Pakistani Rupee', code: 'PKR', symbol: '₨' },
  { name: 'Argentine Peso', code: 'ARS', symbol: '$' },
  { name: 'Nigerian Naira', code: 'NGN', symbol: '₦' },
  { name: 'Kuwaiti Dinar', code: 'KWD', symbol: 'د.ك' },
  { name: 'Moroccan Dirham', code: 'MAD', symbol: 'د.م.' },
  { name: 'Icelandic Króna', code: 'ISK', symbol: 'kr' },
  { name: 'Croatian Kuna', code: 'HRK', symbol: 'kn' },
  { name: 'Bulgarian Lev', code: 'BGN', symbol: 'лв' },
  { name: 'Lebanese Pound', code: 'LBP', symbol: 'ل.ل' },
  { name: 'Serbian Dinar', code: 'RSD', symbol: 'дин' },
  { name: 'Qatari Riyal', code: 'QAR', symbol: 'ر.ق' },
  { name: 'Kenyan Shilling', code: 'KES', symbol: 'KSh' },
  { name: 'Ethiopian Birr', code: 'ETB', symbol: 'Br' },
  { name: 'Dominican Peso', code: 'DOP', symbol: 'RD$' },
  { name: 'Guatemalan Quetzal', code: 'GTQ', symbol: 'Q' },
  { name: 'Costa Rican Colón', code: 'CRC', symbol: '₡' },
  { name: 'Uruguayan Peso', code: 'UYU', symbol: '$U' },
  { name: 'Panamanian Balboa', code: 'PAB', symbol: 'B/.' },
  { name: 'Omani Rial', code: 'OMR', symbol: 'ر.ع.' },
  { name: 'Bolivian Boliviano', code: 'BOB', symbol: 'Bs' },
  { name: 'Paraguayan Guarani', code: 'PYG', symbol: '₲' },
  { name: 'Bahraini Dinar', code: 'BHD', symbol: 'ب.د' },
  { name: 'Trinidad and Tobago Dollar', code: 'TTD', symbol: 'TT$' },
  { name: 'Jordanian Dinar', code: 'JOD', symbol: 'د.ا' },
  { name: 'Georgian Lari', code: 'GEL', symbol: '₾' },
  { name: 'Armenian Dram', code: 'AMD', symbol: '֏' },
  { name: 'Algerian Dinar', code: 'DZD', symbol: 'د.ج' },
  { name: 'Tunisian Dinar', code: 'TND', symbol: 'د.ت' },
  { name: 'Macedonian Denar', code: 'MKD', symbol: 'ден' },
  { name: 'Albanian Lek', code: 'ALL', symbol: 'L' },
  { name: 'Bosnia-Herzegovina Convertible Mark', code: 'BAM', symbol: 'KM' },
  { name: 'Mauritian Rupee', code: 'MUR', symbol: '₨' },
  { name: 'Sri Lankan Rupee', code: 'LKR', symbol: 'Rs' },
  { name: 'Nepalese Rupee', code: 'NPR', symbol: '₨' },
  { name: 'Kazakhstani Tenge', code: 'KZT', symbol: '₸' },
  { name: 'Mongolian Tugrik', code: 'MNT', symbol: '₮' },
  { name: 'Azerbaijani Manat', code: 'AZN', symbol: '₼' },
  { name: 'Belarusian Ruble', code: 'BYN', symbol: 'Br' },
  { name: 'Tajikistani Somoni', code: 'TJS', symbol: 'ЅМ' },
  { name: 'Turkmenistani Manat', code: 'TMT', symbol: 'T' },
  { name: 'Uzbekistani Som', code: 'UZS', symbol: 'soʻm' },
  { name: 'Afghan Afghani', code: 'AFN', symbol: '؋' },
  { name: 'Iraqi Dinar', code: 'IQD', symbol: 'ع.د' },
  { name: 'Syrian Pound', code: 'SYP', symbol: '£S' },
  { name: 'Yemeni Rial', code: 'YER', symbol: '﷼' },
  { name: 'Somali Shilling', code: 'SOS', symbol: 'Sh' },
  { name: 'Sudanese Pound', code: 'SDG', symbol: 'ج.س.' },
  { name: 'Tanzanian Shilling', code: 'TZS', symbol: 'Sh' },
  { name: 'Ugandan Shilling', code: 'UGX', symbol: 'Sh' },
  { name: 'Rwandan Franc', code: 'RWF', symbol: 'FRw' },
  { name: 'Burundian Franc', code: 'BIF', symbol: 'FBu' },
  { name: 'Central African CFA Franc', code: 'XAF', symbol: 'FCFA' },
  { name: 'West African CFA Franc', code: 'XOF', symbol: 'CFA' },
  { name: 'CFP Franc', code: 'XPF', symbol: '₣' },
  { name: 'Cambodian Riel', code: 'KHR', symbol: '៛' },
  { name: 'Lao Kip', code: 'LAK', symbol: '₭' },
  { name: 'Myanmar Kyat', code: 'MMK', symbol: 'K' },
  { name: 'Brunei Dollar', code: 'BND', symbol: 'B$' },
  { name: 'Fijian Dollar', code: 'FJD', symbol: 'FJ$' },
  { name: 'Solomon Islands Dollar', code: 'SBD', symbol: 'SI$' },
  { name: 'Vanuatu Vatu', code: 'VUV', symbol: 'VT' },
  { name: 'Samoan Tala', code: 'WST', symbol: 'T' },
  { name: 'Tongan Paʻanga', code: 'TOP', symbol: 'T$' },
  { name: 'Barbadian Dollar', code: 'BBD', symbol: 'Bds$' },
  { name: 'Belize Dollar', code: 'BZD', symbol: 'BZ$' },
  { name: 'Bermudian Dollar', code: 'BMD', symbol: 'BD$' },
  { name: 'Cayman Islands Dollar', code: 'KYD', symbol: 'CI$' },
  { name: 'Bahamian Dollar', code: 'BSD', symbol: 'B$' },
  { name: 'Jamaican Dollar', code: 'JMD', symbol: 'J$' },
  { name: 'Aruban Florin', code: 'AWG', symbol: 'ƒ' },
  { name: 'Netherlands Antillean Guilder', code: 'ANG', symbol: 'ƒ' },
  { name: 'Surinamese Dollar', code: 'SRD', symbol: '$' },
  { name: 'Guyanese Dollar', code: 'GYD', symbol: 'G$' },
  { name: 'Haitian Gourde', code: 'HTG', symbol: 'G' },
  { name: 'Honduran Lempira', code: 'HNL', symbol: 'L' },
  { name: 'Nicaraguan Córdoba', code: 'NIO', symbol: 'C$' },
  { name: 'Salvadoran Colón', code: 'SVC', symbol: '₡' },
  { name: 'Papua New Guinean Kina', code: 'PGK', symbol: 'K' },
  { name: 'Faroese Króna', code: 'FOK', symbol: 'kr' },
  { name: 'Gibraltar Pound', code: 'GIP', symbol: '£' },
  { name: 'Manx Pound', code: 'IMP', symbol: '£' },
  { name: 'Jersey Pound', code: 'JEP', symbol: '£' },
  { name: 'Cook Islands Dollar', code: 'CKD', symbol: '$' },
  { name: 'Ni-Vanuatu Vatu', code: 'VUV', symbol: 'VT' },
  { name: 'Eritrean Nakfa', code: 'ERN', symbol: 'Nfk' },
  { name: 'Seychellois Rupee', code: 'SCR', symbol: '₨' },
  { name: 'Djiboutian Franc', code: 'DJF', symbol: 'Fdj' },
  { name: 'Comorian Franc', code: 'KMF', symbol: 'CF' },
  { name: 'Malagasy Ariary', code: 'MGA', symbol: 'Ar' },
  { name: 'Malawian Kwacha', code: 'MWK', symbol: 'MK' },
  { name: 'Zambian Kwacha', code: 'ZMW', symbol: 'ZK' },
  { name: 'Namibian Dollar', code: 'NAD', symbol: 'N$' },
  { name: 'Lesotho Loti', code: 'LSL', symbol: 'L' },
  { name: 'Swazi Lilangeni', code: 'SZL', symbol: 'L' },
  { name: 'Botswana Pula', code: 'BWP', symbol: 'P' },
  { name: 'Gambian Dalasi', code: 'GMD', symbol: 'D' },
  { name: 'Sierra Leonean Leone', code: 'SLL', symbol: 'Le' },
  { name: 'Liberian Dollar', code: 'LRD', symbol: 'L$' },
  { name: 'Ghanaian Cedi', code: 'GHS', symbol: '₵' },
  { name: 'Nigerian Naira', code: 'NGN', symbol: '₦' },
  { name: 'Congolese Franc', code: 'CDF', symbol: 'FC' },
  { name: 'Burundian Franc', code: 'BIF', symbol: 'FBu' },
  { name: 'Rwandan Franc', code: 'RWF', symbol: 'FRw' },
  { name: 'Bitcoin', code: 'BTC', symbol: '₿' },
  { name: 'Ethereum', code: 'ETH', symbol: 'Ξ' },
  { name: 'Litecoin', code: 'LTC', symbol: 'Ł' }
];

//TimeFormats
const timeFormats = [
  { _id: new mongoose.Types.ObjectId("6896cdb0e6b84ea7ea5e9177"), name: "H:i:s", format: "H:i:s", isActive: true, isDeleted: false },
  { _id: new mongoose.Types.ObjectId("6896cdb0e6b84ea7ea5e9178"), name: "H:i", format: "H:i", isActive: true, isDeleted: false },
  { _id: new mongoose.Types.ObjectId("6896cdb0e6b84ea7ea5e9179"), name: "G:i:s", format: "G:i:s", isActive: true, isDeleted: false },
  { _id: new mongoose.Types.ObjectId("6896cdb0e6b84ea7ea5e917a"), name: "G:i", format: "G:i", isActive: true, isDeleted: false },
  { _id: new mongoose.Types.ObjectId("6896cdb0e6b84ea7ea5e917b"), name: "h:i:s A", format: "h:i:s A", isActive: true, isDeleted: false },
  { _id: new mongoose.Types.ObjectId("6896cdb0e6b84ea7ea5e917c"), name: "h:i A", format: "h:i A", isActive: true, isDeleted: false },
  { _id: new mongoose.Types.ObjectId("6896cdb0e6b84ea7ea5e917d"), name: "g:i:s A", format: "g:i:s A", isActive: true, isDeleted: false },
  { _id: new mongoose.Types.ObjectId("6896cdb0e6b84ea7ea5e917e"), name: "g:i A", format: "g:i A", isActive: true, isDeleted: false },
  { _id: new mongoose.Types.ObjectId("6896cdb0e6b84ea7ea5e917f"), name: "h:i:s a", format: "h:i:s a", isActive: true, isDeleted: false },
  { _id: new mongoose.Types.ObjectId("6896cdb0e6b84ea7ea5e9180"), name: "g:i:s a", format: "g:i:s a", isActive: true, isDeleted: false },
];

// DateFormats
const dateFormats = [
  { title: "YYYY-MM-DD", format: "YYYY-MM-DD" },
  { title: "DD-MM-YYYY", format: "DD-MM-YYYY" },
  { title: "MM-DD-YYYY", format: "MM-DD-YYYY" },
  { title: "DD/MM/YYYY", format: "DD/MM/YYYY" },
  { title: "MM/DD/YYYY", format: "MM/DD/YYYY" },
  { title: "YYYY/MM/DD", format: "YYYY/MM/DD" },
  { title: "DD Mon YYYY", format: "DD MMM YYYY" },
  { title: "Mon DD, YYYY", format: "MMM DD, YYYY" },
  { title: "YYYY Mon DD", format: "YYYY MMM DD" },
  { title: "DD FullMonth YYYY", format: "DD MMMM YYYY" },
  { title: "FullMonth DD, YYYY", format: "MMMM DD, YYYY" },
  { title: "YYYY FullMonth DD", format: "YYYY MMMM DD" },
  { title: "DD/MM/YY", format: "DD/MM/YY" },
  { title: "MM/DD/YY", format: "MM/DD/YY" },
  { title: "YY/MM/DD", format: "YY/MM/DD" }
].map(item => ({ ...item, isActive: true, isDeleted: false }));

// Timezones
const timezones = [
  { name: "Europe/Amsterdam", utc_offset: "+01:00" },
  { name: "Europe/Andorra", utc_offset: "+01:00" },
  { name: "Europe/Athens", utc_offset: "+02:00" },
  { name: "Europe/Belgrade", utc_offset: "+01:00" },
  { name: "Europe/Berlin", utc_offset: "+01:00" },
  { name: "Europe/Bratislava", utc_offset: "+01:00" },
  { name: "Europe/Brussels", utc_offset: "+01:00" },
  { name: "Europe/Bucharest", utc_offset: "+02:00" },
  { name: "Europe/Budapest", utc_offset: "+01:00" },
  { name: "Europe/Busingen", utc_offset: "+01:00" },
  { name: "Europe/Chisinau", utc_offset: "+02:00" },
  { name: "Europe/Copenhagen", utc_offset: "+01:00" },
  { name: "Europe/Dublin", utc_offset: "+01:00" },
  { name: "Europe/Gibraltar", utc_offset: "+01:00" },
  { name: "Europe/Guernsey", utc_offset: "+01:00" },
  { name: "Europe/Helsinki", utc_offset: "+02:00" },
  { name: "Europe/Isle_of_Man", utc_offset: "+01:00" },
  { name: "Europe/Istanbul", utc_offset: "+03:00" },
  { name: "Europe/Jersey", utc_offset: "+01:00" },
  { name: "Europe/Kaliningrad", utc_offset: "+02:00" },
  { name: "Europe/Kiev", utc_offset: "+02:00" },
  { name: "Europe/Lisbon", utc_offset: "+01:00" },
  { name: "Europe/Ljubljana", utc_offset: "+01:00" },
  { name: "Europe/London", utc_offset: "+01:00" },
  { name: "Europe/Luxembourg", utc_offset: "+01:00" },
  { name: "Europe/Madrid", utc_offset: "+01:00" },
  { name: "Europe/Malta", utc_offset: "+01:00" },
  { name: "Europe/Mariehamn", utc_offset: "+02:00" },
  { name: "Europe/Minsk", utc_offset: "+03:00" },
  { name: "Europe/Monaco", utc_offset: "+01:00" },
  { name: "Europe/Moscow", utc_offset: "+03:00" },
  { name: "Europe/Oslo", utc_offset: "+01:00" },
  { name: "Europe/Paris", utc_offset: "+01:00" },
  { name: "Europe/Podgorica", utc_offset: "+01:00" },
  { name: "Europe/Prague", utc_offset: "+01:00" },
  { name: "Europe/Riga", utc_offset: "+02:00" },
  { name: "Europe/Rome", utc_offset: "+01:00" },
  { name: "Europe/San_Marino", utc_offset: "+01:00" },
  { name: "Europe/Sarajevo", utc_offset: "+01:00" },
  { name: "Europe/Simferopol", utc_offset: "+03:00" },
  { name: "Europe/Skopje", utc_offset: "+01:00" },
  { name: "Europe/Sofia", utc_offset: "+02:00" },
  { name: "Europe/Stockholm", utc_offset: "+01:00" },
  { name: "Europe/Tallinn", utc_offset: "+02:00" },
  { name: "Europe/Tirane", utc_offset: "+01:00" },
  { name: "Europe/Uzhgorod", utc_offset: "+02:00" },
  { name: "Europe/Vaduz", utc_offset: "+01:00" },
  { name: "Europe/Vatican", utc_offset: "+01:00" },
  { name: "Europe/Vienna", utc_offset: "+01:00" },
  { name: "Europe/Vilnius", utc_offset: "+02:00" },
  { name: "Europe/Volgograd", utc_offset: "+03:00" },
  { name: "Europe/Warsaw", utc_offset: "+01:00" },
  { name: "Europe/Zagreb", utc_offset: "+01:00" },
  { name: "Europe/Zaporozhye", utc_offset: "+02:00" },
  { name: "Europe/Zurich", utc_offset: "+01:00" },

  // Africa
  { name: "Africa/Abidjan", utc_offset: "+00:00" },
  { name: "Africa/Accra", utc_offset: "+00:00" },
  { name: "Africa/Addis_Ababa", utc_offset: "+03:00" },
  { name: "Africa/Algiers", utc_offset: "+01:00" },
  { name: "Africa/Asmara", utc_offset: "+03:00" },
  { name: "Africa/Bamako", utc_offset: "+00:00" },
  { name: "Africa/Bangui", utc_offset: "+01:00" },
  { name: "Africa/Banjul", utc_offset: "+00:00" },
  { name: "Africa/Bissau", utc_offset: "+00:00" },
  { name: "Africa/Blantyre", utc_offset: "+02:00" },
  { name: "Africa/Brazzaville", utc_offset: "+01:00" },
  { name: "Africa/Bujumbura", utc_offset: "+02:00" },
  { name: "Africa/Cairo", utc_offset: "+02:00" },
  { name: "Africa/Casablanca", utc_offset: "+01:00" },
  { name: "Africa/Ceuta", utc_offset: "+01:00" },
  { name: "Africa/Conakry", utc_offset: "+00:00" },
  { name: "Africa/Dakar", utc_offset: "+00:00" },
  { name: "Africa/Dar_es_Salaam", utc_offset: "+03:00" },
  { name: "Africa/Djibouti", utc_offset: "+03:00" },
  { name: "Africa/Douala", utc_offset: "+01:00" },
  { name: "Africa/El_Aaiun", utc_offset: "+01:00" },
  { name: "Africa/Freetown", utc_offset: "+00:00" },
  { name: "Africa/Gaborone", utc_offset: "+02:00" },
  { name: "Africa/Harare", utc_offset: "+02:00" },
  { name: "Africa/Johannesburg", utc_offset: "+02:00" },
  { name: "Africa/Juba", utc_offset: "+02:00" },
  { name: "Africa/Kampala", utc_offset: "+03:00" },
  { name: "Africa/Khartoum", utc_offset: "+02:00" },
  { name: "Africa/Kigali", utc_offset: "+02:00" },
  { name: "Africa/Kinshasa", utc_offset: "+01:00" },
  { name: "Africa/Lagos", utc_offset: "+01:00" },
  { name: "Africa/Libreville", utc_offset: "+01:00" },
  { name: "Africa/Lome", utc_offset: "+00:00" },
  { name: "Africa/Luanda", utc_offset: "+01:00" },
  { name: "Africa/Lubumbashi", utc_offset: "+02:00" },
  { name: "Africa/Lusaka", utc_offset: "+02:00" },
  { name: "Africa/Malabo", utc_offset: "+01:00" },
  { name: "Africa/Maputo", utc_offset: "+02:00" },
  { name: "Africa/Maseru", utc_offset: "+02:00" },
  { name: "Africa/Mbabane", utc_offset: "+02:00" },
  { name: "Africa/Mogadishu", utc_offset: "+03:00" },
  { name: "Africa/Monrovia", utc_offset: "+00:00" },
  { name: "Africa/Nairobi", utc_offset: "+03:00" },
  { name: "Africa/Ndjamena", utc_offset: "+01:00" },
  { name: "Africa/Niamey", utc_offset: "+01:00" },
  { name: "Africa/Nouakchott", utc_offset: "+00:00" },
  { name: "Africa/Ouagadougou", utc_offset: "+00:00" },
  { name: "Africa/Porto-Novo", utc_offset: "+01:00" },
  { name: "Africa/Sao_Tome", utc_offset: "+00:00" },
  { name: "Africa/Tripoli", utc_offset: "+02:00" },
  { name: "Africa/Tunis", utc_offset: "+01:00" },
  { name: "Africa/Windhoek", utc_offset: "+02:00" },

  // America
  { name: "America/Adak", utc_offset: "-09:00" },
  { name: "America/Anchorage", utc_offset: "-08:00" },
  { name: "America/Anguilla", utc_offset: "-04:00" },
  { name: "America/Antigua", utc_offset: "-04:00" },
  { name: "America/Araguaina", utc_offset: "-03:00" },
  { name: "America/Argentina/Buenos_Aires", utc_offset: "-03:00" },
  { name: "America/Argentina/Catamarca", utc_offset: "-03:00" },
  { name: "America/Argentina/Cordoba", utc_offset: "-03:00" },
  { name: "America/Argentina/Jujuy", utc_offset: "-03:00" },
  { name: "America/Argentina/La_Rioja", utc_offset: "-03:00" },
  { name: "America/Argentina/Mendoza", utc_offset: "-03:00" },
  { name: "America/Argentina/Rio_Gallegos", utc_offset: "-03:00" },
  { name: "America/Argentina/Salta", utc_offset: "-03:00" },
  { name: "America/Argentina/San_Juan", utc_offset: "-03:00" },
  { name: "America/Argentina/San_Luis", utc_offset: "-03:00" },
  { name: "America/Argentina/Tucuman", utc_offset: "-03:00" },
  { name: "America/Argentina/Ushuaia", utc_offset: "-03:00" },
  { name: "America/Aruba", utc_offset: "-04:00" },
  { name: "America/Asuncion", utc_offset: "-04:00" },
  { name: "America/Atikokan", utc_offset: "-05:00" },
  { name: "America/Bahia", utc_offset: "-03:00" },
  { name: "America/Bahia_Banderas", utc_offset: "-06:00" },
  { name: "America/Barbados", utc_offset: "-04:00" },
  { name: "America/Belem", utc_offset: "-03:00" },
  { name: "America/Belize", utc_offset: "-06:00" },
  { name: "America/Blanc-Sablon", utc_offset: "-04:00" },
  { name: "America/Boa_Vista", utc_offset: "-04:00" },
  { name: "America/Bogota", utc_offset: "-05:00" },
  { name: "America/Boise", utc_offset: "-06:00" },
  { name: "America/Cambridge_Bay", utc_offset: "-06:00" },
  { name: "America/Campo_Grande", utc_offset: "-04:00" },
  { name: "America/Cancun", utc_offset: "-05:00" },
  { name: "America/Caracas", utc_offset: "-04:00" },
  { name: "America/Cayenne", utc_offset: "-03:00" },
  { name: "America/Cayman", utc_offset: "-05:00" },
  { name: "America/Chicago", utc_offset: "-05:00" },
  { name: "America/Chihuahua", utc_offset: "-06:00" },
  { name: "America/Costa_Rica", utc_offset: "-06:00" },
  { name: "America/Creston", utc_offset: "-07:00" },
  { name: "America/Cuiaba", utc_offset: "-04:00" },
  { name: "America/Curacao", utc_offset: "-04:00" },
  { name: "America/Danmarkshavn", utc_offset: "+00:00" },
  { name: "America/Dawson", utc_offset: "-07:00" },
  { name: "America/Dawson_Creek", utc_offset: "-07:00" },
  { name: "America/Denver", utc_offset: "-06:00" },
  { name: "America/Detroit", utc_offset: "-04:00" },
  { name: "America/Dominica", utc_offset: "-04:00" },
  { name: "America/Edmonton", utc_offset: "-06:00" },
  { name: "America/Eirunepe", utc_offset: "-05:00" },
  { name: "America/El_Salvador", utc_offset: "-06:00" },
  { name: "America/Fort_Nelson", utc_offset: "-07:00" },
  { name: "America/Fortaleza", utc_offset: "-03:00" },
  { name: "America/Glace_Bay", utc_offset: "-03:00" },
  { name: "America/Godthab", utc_offset: "-02:00" },
  { name: "America/Goose_Bay", utc_offset: "-03:00" },
  { name: "America/Grand_Turk", utc_offset: "-04:00" },
  { name: "America/Grenada", utc_offset: "-04:00" },
  { name: "America/Guadeloupe", utc_offset: "-04:00" },
  { name: "America/Guatemala", utc_offset: "-06:00" },
  { name: "America/Guayaquil", utc_offset: "-05:00" },
  { name: "America/Guyana", utc_offset: "-04:00" },
  { name: "America/Halifax", utc_offset: "-03:00" },
  { name: "America/Havana", utc_offset: "-04:00" },
  { name: "America/Hermosillo", utc_offset: "-07:00" },
  { name: "America/Indiana/Indianapolis", utc_offset: "-04:00" },
  { name: "America/Indiana/Knox", utc_offset: "-05:00" },
  { name: "America/Indiana/Marengo", utc_offset: "-04:00" },
  { name: "America/Indiana/Petersburg", utc_offset: "-04:00" },
  { name: "America/Indiana/Tell_City", utc_offset: "-05:00" },
  { name: "America/Indiana/Vevay", utc_offset: "-04:00" },
  { name: "America/Indiana/Vincennes", utc_offset: "-04:00" },
  { name: "America/Indiana/Winamac", utc_offset: "-04:00" },
  { name: "America/Inuvik", utc_offset: "-06:00" },
  { name: "America/Iqaluit", utc_offset: "-04:00" },
  { name: "America/Jamaica", utc_offset: "-05:00" },
  { name: "America/Juneau", utc_offset: "-08:00" },
  { name: "America/Kentucky/Louisville", utc_offset: "-04:00" },
  { name: "America/Kentucky/Monticello", utc_offset: "-04:00" },
  { name: "America/Kralendijk", utc_offset: "-04:00" },
  { name: "America/La_Paz", utc_offset: "-04:00" },
  { name: "America/Lima", utc_offset: "-05:00" },
  { name: "America/Los_Angeles", utc_offset: "-07:00" },
  { name: "America/Lower_Princes", utc_offset: "-04:00" },
  { name: "America/Maceio", utc_offset: "-03:00" },
  { name: "America/Managua", utc_offset: "-06:00" },
  { name: "America/Manaus", utc_offset: "-04:00" },
  { name: "America/Marigot", utc_offset: "-04:00" },
  { name: "America/Martinique", utc_offset: "-04:00" },
  { name: "America/Matamoros", utc_offset: "-05:00" },
  { name: "America/Mazatlan", utc_offset: "-06:00" },
  { name: "America/Menominee", utc_offset: "-05:00" },
  { name: "America/Merida", utc_offset: "-05:00" },
  { name: "America/Metlakatla", utc_offset: "-08:00" },
  { name: "America/Mexico_City", utc_offset: "-05:00" },
  { name: "America/Miquelon", utc_offset: "-02:00" },
  { name: "America/Moncton", utc_offset: "-03:00" },
  { name: "America/Monterrey", utc_offset: "-05:00" },
  { name: "America/Montevideo", utc_offset: "-03:00" },
  { name: "America/Montreal", utc_offset: "-04:00" },
  { name: "America/Montserrat", utc_offset: "-04:00" },
  { name: "America/Nassau", utc_offset: "-04:00" },
  { name: "America/New_York", utc_offset: "-04:00" },
  { name: "America/Nipigon", utc_offset: "-04:00" },
  { name: "America/Nome", utc_offset: "-08:00" },
  { name: "America/Noronha", utc_offset: "-02:00" },
  { name: "America/North_Dakota/Beulah", utc_offset: "-05:00" },
  { name: "America/North_Dakota/Center", utc_offset: "-05:00" },
  { name: "America/North_Dakota/New_Salem", utc_offset: "-05:00" },
  { name: "America/Ojinaga", utc_offset: "-06:00" },
  { name: "America/Panama", utc_offset: "-05:00" },
  { name: "America/Pangnirtung", utc_offset: "-04:00" },
  { name: "America/Paramaribo", utc_offset: "-03:00" },
  { name: "America/Phoenix", utc_offset: "-07:00" },
  { name: "America/Port-au-Prince", utc_offset: "-04:00" },
  { name: "America/Port_of_Spain", utc_offset: "-04:00" },
  { name: "America/Porto_Velho", utc_offset: "-04:00" },
  { name: "America/Puerto_Rico", utc_offset: "-04:00" },
  { name: "America/Punta_Arenas", utc_offset: "-03:00" },
  { name: "America/Rainy_River", utc_offset: "-05:00" },
  { name: "America/Rankin_Inlet", utc_offset: "-05:00" },
  { name: "America/Recife", utc_offset: "-03:00" },
  { name: "America/Regina", utc_offset: "-06:00" },
  { name: "America/Resolute", utc_offset: "-05:00" },
  { name: "America/Rio_Branco", utc_offset: "-05:00" },
  { name: "America/Santarem", utc_offset: "-03:00" },
  { name: "America/Santiago", utc_offset: "-04:00" },
  { name: "America/Santo_Domingo", utc_offset: "-04:00" },
  { name: "America/Sao_Paulo", utc_offset: "-03:00" },
  { name: "America/Scoresbysund", utc_offset: "+00:00" },
  { name: "America/Sitka", utc_offset: "-08:00" },
  { name: "America/St_Barthelemy", utc_offset: "-04:00" },
  { name: "America/St_Johns", utc_offset: "-02:30" },
  { name: "America/St_Kitts", utc_offset: "-04:00" },
  { name: "America/St_Lucia", utc_offset: "-04:00" },
  { name: "America/St_Thomas", utc_offset: "-04:00" },
  { name: "America/St_Vincent", utc_offset: "-04:00" },
  { name: "America/Swift_Current", utc_offset: "-06:00" },
  { name: "America/Tegucigalpa", utc_offset: "-06:00" },
  { name: "America/Thule", utc_offset: "-03:00" },
  { name: "America/Thunder_Bay", utc_offset: "-04:00" },
  { name: "America/Tijuana", utc_offset: "-07:00" },
  { name: "America/Toronto", utc_offset: "-04:00" },
  { name: "America/Tortola", utc_offset: "-04:00" },
  { name: "America/Vancouver", utc_offset: "-07:00" },
  { name: "America/Whitehorse", utc_offset: "-07:00" },
  { name: "America/Winnipeg", utc_offset: "-05:00" },
  { name: "America/Yakutat", utc_offset: "-08:00" },
  { name: "America/Yellowknife", utc_offset: "-06:00" },

  // Asia
  { name: "Asia/Aden", utc_offset: "+03:00" },
  { name: "Asia/Almaty", utc_offset: "+06:00" },
  { name: "Asia/Amman", utc_offset: "+03:00" },
  { name: "Asia/Anadyr", utc_offset: "+12:00" },
  { name: "Asia/Aqtau", utc_offset: "+05:00" },
  { name: "Asia/Aqtobe", utc_offset: "+05:00" },
  { name: "Asia/Ashgabat", utc_offset: "+05:00" },
  { name: "Asia/Atyrau", utc_offset: "+05:00" },
  { name: "Asia/Baghdad", utc_offset: "+03:00" },
  { name: "Asia/Bahrain", utc_offset: "+03:00" },
  { name: "Asia/Baku", utc_offset: "+04:00" },
  { name: "Asia/Bangkok", utc_offset: "+07:00" },
  { name: "Asia/Barnaul", utc_offset: "+07:00" },
  { name: "Asia/Beirut", utc_offset: "+03:00" },
  { name: "Asia/Bishkek", utc_offset: "+06:00" },
  { name: "Asia/Brunei", utc_offset: "+08:00" },
  { name: "Asia/Chita", utc_offset: "+09:00" },
  { name: "Asia/Choibalsan", utc_offset: "+08:00" },
  { name: "Asia/Colombo", utc_offset: "+05:30" },
  { name: "Asia/Damascus", utc_offset: "+03:00" },
  { name: "Asia/Dhaka", utc_offset: "+06:00" },
  { name: "Asia/Dili", utc_offset: "+09:00" },
  { name: "Asia/Dubai", utc_offset: "+04:00" },
  { name: "Asia/Dushanbe", utc_offset: "+05:00" },
  { name: "Asia/Famagusta", utc_offset: "+03:00" },
  { name: "Asia/Gaza", utc_offset: "+03:00" },
  { name: "Asia/Hebron", utc_offset: "+03:00" },
  { name: "Asia/Ho_Chi_Minh", utc_offset: "+07:00" },
  { name: "Asia/Hong_Kong", utc_offset: "+08:00" },
  { name: "Asia/Hovd", utc_offset: "+07:00" },
  { name: "Asia/Irkutsk", utc_offset: "+08:00" },
  { name: "Asia/Jakarta", utc_offset: "+07:00" },
  { name: "Asia/Jayapura", utc_offset: "+09:00" },
  { name: "Asia/Jerusalem", utc_offset: "+03:00" },
  { name: "Asia/Kabul", utc_offset: "+04:30" },
  { name: "Asia/Kamchatka", utc_offset: "+12:00" },
  { name: "Asia/Karachi", utc_offset: "+05:00" },
  { name: "Asia/Kathmandu", utc_offset: "+05:45" },
  { name: "Asia/Khandyga", utc_offset: "+09:00" },
  { name: "Asia/Kolkata", utc_offset: "+05:30" },
  { name: "Asia/Krasnoyarsk", utc_offset: "+07:00" },
  { name: "Asia/Kuala_Lumpur", utc_offset: "+08:00" },
  { name: "Asia/Kuching", utc_offset: "+08:00" },
  { name: "Asia/Kuwait", utc_offset: "+03:00" },
  { name: "Asia/Macau", utc_offset: "+08:00" },
  { name: "Asia/Magadan", utc_offset: "+11:00" },
  { name: "Asia/Makassar", utc_offset: "+08:00" },
  { name: "Asia/Manila", utc_offset: "+08:00" },
  { name: "Asia/Muscat", utc_offset: "+04:00" },
  { name: "Asia/Nicosia", utc_offset: "+03:00" },
  { name: "Asia/Novokuznetsk", utc_offset: "+07:00" },
  { name: "Asia/Novosibirsk", utc_offset: "+07:00" },
  { name: "Asia/Omsk", utc_offset: "+06:00" },
  { name: "Asia/Oral", utc_offset: "+05:00" },
  { name: "Asia/Phnom_Penh", utc_offset: "+07:00" },
  { name: "Asia/Pontianak", utc_offset: "+07:00" },
  { name: "Asia/Pyongyang", utc_offset: "+09:00" },
  { name: "Asia/Qatar", utc_offset: "+03:00" },
  { name: "Asia/Qostanay", utc_offset: "+06:00" },
  { name: "Asia/Qyzylorda", utc_offset: "+05:00" },
  { name: "Asia/Riyadh", utc_offset: "+03:00" },
  { name: "Asia/Sakhalin", utc_offset: "+11:00" },
  { name: "Asia/Samarkand", utc_offset: "+05:00" },
  { name: "Asia/Seoul", utc_offset: "+09:00" },
  { name: "Asia/Shanghai", utc_offset: "+08:00" },
  { name: "Asia/Singapore", utc_offset: "+08:00" },
  { name: "Asia/Srednekolymsk", utc_offset: "+11:00" },
  { name: "Asia/Taipei", utc_offset: "+08:00" },
  { name: "Asia/Tashkent", utc_offset: "+05:00" },
  { name: "Asia/Tbilisi", utc_offset: "+04:00" },
  { name: "Asia/Tehran", utc_offset: "+03:30" },
  { name: "Asia/Thimphu", utc_offset: "+06:00" },
  { name: "Asia/Tokyo", utc_offset: "+09:00" },
  { name: "Asia/Tomsk", utc_offset: "+07:00" },
  { name: "Asia/Ulaanbaatar", utc_offset: "+08:00" },
  { name: "Asia/Urumqi", utc_offset: "+06:00" },
  { name: "Asia/Ust-Nera", utc_offset: "+10:00" },
  { name: "Asia/Vientiane", utc_offset: "+07:00" },
  { name: "Asia/Vladivostok", utc_offset: "+10:00" },
  { name: "Asia/Yakutsk", utc_offset: "+09:00" },
  { name: "Asia/Yangon", utc_offset: "+06:30" },
  { name: "Asia/Yekaterinburg", utc_offset: "+05:00" },
  { name: "Asia/Yerevan", utc_offset: "+04:00" },

  // Australia & Oceania
  { name: "Australia/Adelaide", utc_offset: "+09:30" },
  { name: "Australia/Brisbane", utc_offset: "+10:00" },
  { name: "Australia/Broken_Hill", utc_offset: "+09:30" },
  { name: "Australia/Currie", utc_offset: "+10:00" },
  { name: "Australia/Darwin", utc_offset: "+09:30" },
  { name: "Australia/Eucla", utc_offset: "+08:45" },
  { name: "Australia/Hobart", utc_offset: "+10:00" },
  { name: "Australia/Lindeman", utc_offset: "+10:00" },
  { name: "Australia/Lord_Howe", utc_offset: "+10:30" },
  { name: "Australia/Melbourne", utc_offset: "+10:00" },
  { name: "Australia/Perth", utc_offset: "+08:00" },
  { name: "Australia/Sydney", utc_offset: "+10:00" },

  // Pacific
  { name: "Pacific/Apia", utc_offset: "+13:00" },
  { name: "Pacific/Auckland", utc_offset: "+12:00" },
  { name: "Pacific/Bougainville", utc_offset: "+11:00" },
  { name: "Pacific/Chatham", utc_offset: "+12:45" },
  { name: "Pacific/Chuuk", utc_offset: "+10:00" },
  { name: "Pacific/Easter", utc_offset: "-06:00" },
  { name: "Pacific/Efate", utc_offset: "+11:00" },
  { name: "Pacific/Enderbury", utc_offset: "+13:00" },
  { name: "Pacific/Fakaofo", utc_offset: "+13:00" },
  { name: "Pacific/Fiji", utc_offset: "+12:00" },
  { name: "Pacific/Funafuti", utc_offset: "+12:00" },
  { name: "Pacific/Galapagos", utc_offset: "-06:00" },
  { name: "Pacific/Gambier", utc_offset: "-09:00" },
  { name: "Pacific/Guadalcanal", utc_offset: "+11:00" },
  { name: "Pacific/Guam", utc_offset: "+10:00" },
  { name: "Pacific/Honolulu", utc_offset: "-10:00" },
  { name: "Pacific/Kiritimati", utc_offset: "+14:00" },
  { name: "Pacific/Kosrae", utc_offset: "+11:00" },
  { name: "Pacific/Kwajalein", utc_offset: "+12:00" },
  { name: "Pacific/Majuro", utc_offset: "+12:00" },
  { name: "Pacific/Marquesas", utc_offset: "-09:30" },
  { name: "Pacific/Midway", utc_offset: "-11:00" },
  { name: "Pacific/Nauru", utc_offset: "+12:00" },
  { name: "Pacific/Niue", utc_offset: "-11:00" },
  { name: "Pacific/Norfolk", utc_offset: "+11:00" },
  { name: "Pacific/Noumea", utc_offset: "+11:00" },
  { name: "Pacific/Pago_Pago", utc_offset: "-11:00" },
  { name: "Pacific/Palau", utc_offset: "+09:00" },
  { name: "Pacific/Pitcairn", utc_offset: "-08:00" },
  { name: "Pacific/Pohnpei", utc_offset: "+11:00" },
  { name: "Pacific/Port_Moresby", utc_offset: "+10:00" },
  { name: "Pacific/Rarotonga", utc_offset: "-10:00" },
  { name: "Pacific/Saipan", utc_offset: "+10:00" },
  { name: "Pacific/Tahiti", utc_offset: "-10:00" },
  { name: "Pacific/Tarawa", utc_offset: "+12:00" },
  { name: "Pacific/Tongatapu", utc_offset: "+13:00" },
  { name: "Pacific/Wake", utc_offset: "+12:00" },
  { name: "Pacific/Wallis", utc_offset: "+12:00" },

  // Other
  { name: "UTC", utc_offset: "+00:00" },
  { name: "GMT", utc_offset: "+00:00" },
  { name: "EST", utc_offset: "-05:00" },
  { name: "MST", utc_offset: "-07:00" },
  { name: "HST", utc_offset: "-10:00" },
  { name: "EST5EDT", utc_offset: "-04:00" },
  { name: "CST6CDT", utc_offset: "-05:00" },
  { name: "MST7MDT", utc_offset: "-06:00" },
  { name: "PST8PDT", utc_offset: "-07:00" }
];

const seedCollection = async (Model, data, label) => {
  const count = await Model.countDocuments();
  if (count === 0) {
    await Model.insertMany(data);
    console.log(`Inserted ${data.length} ${label}`);
  } else {
    console.log(`${label} already exist — skipped`);
  }
};

try {
  await seedCollection(Currency, currencies, 'currencies');
  await seedCollection(DateFormat, dateFormats, 'date formats');
  await seedCollection(TimeFormat, timeFormats, 'time formats');
  await seedCollection(Timezone, timezones, 'timezones');

  console.log(' All seed data inserted successfully!');
  await mongoose.connection.close();
  process.exit(0);
} catch (err) {
  console.error(' Seeding failed:', err);
  await mongoose.connection.close();
  process.exit(1);
}
